name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "github-flask-app-pack"
  EB_APPLICATION_NAME       : "GitHubFlask_lesson"
  EB_ENVIRONMENT_NAME       : "Githubflasklesson-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip" 
  AWS_REGION_NAME           : "eu-north-1"
  
on: 
  push:
    branches: 
      - master
      
jobs:
    my_ci_part:
       runs-on: ubuntu-latest
     
       steps:
       - name: Git clone our repo
         uses: actions/checkout@v1
       
       - name: Create ZIP depl pack 
         run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
